Repository S-C-S-D/ICTicket-BackEnd, pull requests merged in 2024-07, with the labels that each got.

#2 Feat/entity/#1
  src/main/java/com/sparta/icticket/IcTicketApplication.java
  src/main/java/com/sparta/icticket/banner/Banner.java
  src/main/java/com/sparta/icticket/comment/Comment.java
  src/main/java/com/sparta/icticket/common/Timestamped.java
  src/main/java/com/sparta/icticket/common/enums/AgeGroup.java
  src/main/java/com/sparta/icticket/common/enums/BannerType.java
  src/main/java/com/sparta/icticket/common/enums/Genre.java
  src/main/java/com/sparta/icticket/common/enums/OrderStatus.java
  src/main/java/com/sparta/icticket/common/enums/SeatGrade.java
  src/main/java/com/sparta/icticket/common/enums/UserRole.java
  src/main/java/com/sparta/icticket/common/enums/UserStatus.java
  src/main/java/com/sparta/icticket/like/Like.java
  src/main/java/com/sparta/icticket/order/Order.java
  src/main/java/com/sparta/icticket/performance/Performance.java
  src/main/java/com/sparta/icticket/sales/Sales.java
  src/main/java/com/sparta/icticket/seat/Seat.java
  src/main/java/com/sparta/icticket/session/Session.java
  src/main/java/com/sparta/icticket/ticket/Ticket.java
  src/main/java/com/sparta/icticket/user/User.java
  src/main/java/com/sparta/icticket/venue/Venue.java
Labels: Add

#8 Feat/user/#3
  src/main/java/com/sparta/icticket/user/User.java
  src/main/java/com/sparta/icticket/user/UserController.java
  src/main/java/com/sparta/icticket/user/UserRepository.java
  src/main/java/com/sparta/icticket/user/UserService.java
  src/main/java/com/sparta/icticket/user/dto/UserSignupRequestDto.java
Labels: Feat

#11 Feat/security/#9
  http/User.http
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/common/enums/UserRole.java
  src/main/java/com/sparta/icticket/config/SecurityConfig.java
  src/main/java/com/sparta/icticket/security/UserDetailsImpl.java
  src/main/java/com/sparta/icticket/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/icticket/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/sparta/icticket/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/icticket/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/icticket/security/jwt/JwtExceptionFilter.java
  src/main/java/com/sparta/icticket/security/jwt/JwtUtil.java
  src/main/java/com/sparta/icticket/user/User.java
  src/main/java/com/sparta/icticket/user/UserService.java
  src/main/java/com/sparta/icticket/user/dto/LoginRequestDto.java
Labels: Feat

#14 로그아웃
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/common/enums/SuccessStatus.java
  src/main/java/com/sparta/icticket/user/User.java
  src/main/java/com/sparta/icticket/user/UserController.java
  src/main/java/com/sparta/icticket/user/UserService.java
Labels: Feat

#16 Feat/profile/#10
  http/User.http
  src/main/java/com/sparta/icticket/banner/BannerRepository.java
  src/main/java/com/sparta/icticket/comment/CommentRepository.java
  src/main/java/com/sparta/icticket/like/LikeRepository.java
  src/main/java/com/sparta/icticket/order/OrderRepository.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepository.java
  src/main/java/com/sparta/icticket/sales/SalesRepository.java
  src/main/java/com/sparta/icticket/seat/SeatRepository.java
  src/main/java/com/sparta/icticket/session/SessionRepository.java
  src/main/java/com/sparta/icticket/ticket/TicketRepository.java
  src/main/java/com/sparta/icticket/user/User.java
  src/main/java/com/sparta/icticket/user/UserController.java
  src/main/java/com/sparta/icticket/user/UserService.java
  src/main/java/com/sparta/icticket/user/dto/UserProfileRequestDto.java
  src/main/java/com/sparta/icticket/user/dto/UserProfileResponseDto.java
  src/main/java/com/sparta/icticket/venue/VenueRepository.java
Labels: Feat

#21 Feat/admin venue/#7
  src/main/java/com/sparta/icticket/admin/venue/AdminVenueController.java
  src/main/java/com/sparta/icticket/admin/venue/AdminVenueService.java
  src/main/java/com/sparta/icticket/admin/venue/dto/VenueRequestDto.java
  src/main/java/com/sparta/icticket/admin/venue/dto/VenueResponseDto.java
  src/main/java/com/sparta/icticket/venue/Venue.java
Labels: Feat

#24 [Feat] 공연 등록 기능 #22
  http/Performance.http
  http/Venue.http
  src/main/java/com/sparta/icticket/admin/controller/AdminPerformanceController.java
  src/main/java/com/sparta/icticket/admin/controller/AdminVenueController.java
  src/main/java/com/sparta/icticket/admin/service/AdminPerformanceService.java
  src/main/java/com/sparta/icticket/admin/service/AdminVenueService.java
  src/main/java/com/sparta/icticket/admin/venue/dto/VenueResponseDto.java
  src/main/java/com/sparta/icticket/performance/Performance.java
  src/main/java/com/sparta/icticket/performance/dto/PerformanceRequestDto.java
  src/main/java/com/sparta/icticket/session/repository/SessionRepository.java
  src/main/java/com/sparta/icticket/venue/Venue.java
  src/main/java/com/sparta/icticket/venue/dto/VenueRequestDto.java
Labels: Feat

#27 Feat/seat/#23
  http/Seat.http
  http/Session.http
  http/User.http
  src/main/java/com/sparta/icticket/IcTicketApplication.java
  src/main/java/com/sparta/icticket/admin/seat/AdminSeatController.java
  src/main/java/com/sparta/icticket/admin/seat/AdminSeatService.java
  src/main/java/com/sparta/icticket/admin/seat/dto/SeatCreateRequestDto.java
  src/main/java/com/sparta/icticket/common/enums/SeatStatus.java
  src/main/java/com/sparta/icticket/config/JpaConfig.java
  src/main/java/com/sparta/icticket/config/SecurityConfig.java
  src/main/java/com/sparta/icticket/sales/SalesRepository.java
  src/main/java/com/sparta/icticket/seat/Seat.java
  src/main/java/com/sparta/icticket/seat/SeatController.java
  src/main/java/com/sparta/icticket/seat/SeatRepository.java
  src/main/java/com/sparta/icticket/seat/SeatRepositoryQuery.java
  src/main/java/com/sparta/icticket/seat/SeatRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/seat/SeatService.java
  src/main/java/com/sparta/icticket/seat/dto/SeatCountResponseDto.java
  src/main/java/com/sparta/icticket/seat/dto/SeatReservedRequestDto.java
  src/main/java/com/sparta/icticket/seat/dto/SeatReservedResponseDto.java
Labels: Feat

#29 Feat/like/#17
  http/Like.http
  http/User.http
  src/main/java/com/sparta/icticket/admin/controller/AdminSeatController.java
  src/main/java/com/sparta/icticket/admin/service/AdminSeatService.java
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/config/SecurityConfig.java
  src/main/java/com/sparta/icticket/like/Like.java
  src/main/java/com/sparta/icticket/like/LikeController.java
  src/main/java/com/sparta/icticket/like/LikeRepository.java
  src/main/java/com/sparta/icticket/like/LikeService.java
Labels: Feat

#33 Feat/sales/#32
  http/Like.http
  http/Sales.http
  http/Seat.http
  src/main/java/com/sparta/icticket/admin/controller/AdminSalesController.java
  src/main/java/com/sparta/icticket/admin/sales/dto/SalesAddRequestDto.java
  src/main/java/com/sparta/icticket/admin/sales/dto/SalesUpdateRequestDto.java
  src/main/java/com/sparta/icticket/admin/service/AdminSalesService.java
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/common/enums/SuccessStatus.java
  src/main/java/com/sparta/icticket/like/LikeRepository.java
  src/main/java/com/sparta/icticket/like/LikeService.java
  src/main/java/com/sparta/icticket/sales/Sales.java
  src/main/java/com/sparta/icticket/sales/SalesRepository.java
Labels: Feat

#34 Feat/performance/#6 공연 조회
  http/Performance.http
  src/main/java/com/sparta/icticket/config/SecurityConfig.java
  src/main/java/com/sparta/icticket/performance/Performance.java
  src/main/java/com/sparta/icticket/performance/PerformanceController.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepository.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepositoryQuery.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/performance/PerformanceService.java
  src/main/java/com/sparta/icticket/performance/dto/PerformanceDetailResponseDto.java
Labels: Feat

#38 Feat/admin banners/#36
  http/Banner.http
  src/main/java/com/sparta/icticket/admin/controller/AdminBannerController.java
  src/main/java/com/sparta/icticket/admin/service/AdminBannerService.java
  src/main/java/com/sparta/icticket/banner/Banner.java
  src/main/java/com/sparta/icticket/banner/BannerController.java
  src/main/java/com/sparta/icticket/banner/BannerRepository.java
  src/main/java/com/sparta/icticket/banner/BannerService.java
  src/main/java/com/sparta/icticket/banner/dto/BannerRequestDto.java
  src/main/java/com/sparta/icticket/banner/dto/BannerResponseDto.java
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/common/enums/SuccessStatus.java
  src/main/java/com/sparta/icticket/config/SecurityConfig.java
Labels: Feat

#39 Feat/performance/#6
  http/Performance.http
  src/main/java/com/sparta/icticket/performance/PerformanceController.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepositoryQuery.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/performance/PerformanceService.java
  src/main/java/com/sparta/icticket/performance/dto/DiscountPerformanceResponseDto.java
Labels: Fix

#42 [Fix] 공연장 삭제 controller의 requestBody 삭제 #40
  http/Venue.http
  src/main/java/com/sparta/icticket/admin/controller/AdminVenueController.java
  src/main/java/com/sparta/icticket/admin/service/AdminVenueService.java
Labels: Fix

#43 Fix/#41
  http/User.http
  src/main/java/com/sparta/icticket/admin/service/AdminSalesService.java
  src/main/java/com/sparta/icticket/admin/service/AdminSeatService.java
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/sales/SalesRepository.java
  src/main/java/com/sparta/icticket/seat/Seat.java
  src/main/java/com/sparta/icticket/seat/SeatRepository.java
  src/main/java/com/sparta/icticket/user/UserController.java
  src/main/java/com/sparta/icticket/user/UserRepository.java
  src/main/java/com/sparta/icticket/user/UserService.java
Labels: Fix

#45 [Fix] Comment 수정 #44
  src/main/java/com/sparta/icticket/comment/CommentController.java
  src/main/java/com/sparta/icticket/comment/CreateCommentRequestDto.java
Labels: Fix

#49 Feat/scheduler/#30
  src/main/java/com/sparta/icticket/IcTicketApplication.java
  src/main/java/com/sparta/icticket/config/SchedulerConfig.java
  src/main/java/com/sparta/icticket/seat/SeatRepositoryQueryImpl.java
Labels: Feat

#50 feat/performance/#6 추천 공연 조회 오류 수정
  src/main/java/com/sparta/icticket/performance/PerformanceRepositoryQueryImpl.java
Labels: Fix

#52 Test/dummy/#47 더미데이터 추가 테스트 코드
  http/Banner.http
  http/Performance.http
  src/main/java/com/sparta/icticket/performance/Performance.java
  src/main/java/com/sparta/icticket/sales/Sales.java
  src/main/java/com/sparta/icticket/seat/Seat.java
  src/main/java/com/sparta/icticket/session/Session.java
  src/main/java/com/sparta/icticket/user/dto/UserSignupRequestDto.java
  src/main/java/com/sparta/icticket/venue/Venue.java
  src/test/java/com/sparta/icticket/CreateDummyData.java
Labels: Test

#55 Chore/#51
  src/main/java/com/sparta/icticket/admin/controller/AdminSeatController.java
  src/main/java/com/sparta/icticket/admin/service/AdminSeatService.java
  src/main/java/com/sparta/icticket/like/LikeController.java
  src/main/java/com/sparta/icticket/like/LikeService.java
  src/main/java/com/sparta/icticket/order/OrderService.java
  src/main/java/com/sparta/icticket/seat/SeatRepository.java
Labels: Chore

#57 Test/dummy/#47 배너 더미 데이터 추가
  src/main/java/com/sparta/icticket/banner/Banner.java
  src/main/java/com/sparta/icticket/banner/BannerRepository.java
  src/main/java/com/sparta/icticket/banner/BannerService.java
  src/test/java/com/sparta/icticket/CreateDummyData.java
Labels: Test, Chore

#59 [Fix] Security exception 수정 #58
  src/main/java/com/sparta/icticket/config/SecurityConfig.java
  src/main/java/com/sparta/icticket/security/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/icticket/security/jwt/CustomAuthenticationEntryPoint.java
Labels: Fix

#60 [Chore] 더미데이터 유저 이메일 수정 #58
  src/test/java/com/sparta/icticket/CreateDummyData.java
Labels: Chore

#61 [Chore] 더미데이터 유저 이메일 수정 #58
  src/test/java/com/sparta/icticket/CreateDummyData.java
Labels: Fix

#62 [Chore] HttpMessageNotReadableException 예외처리 추가 및 에러타입 정리 #58
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/common/exception/ExceptionManager.java
Labels: Chore

#63 Chore/결제 완료 시 10분이 지났는지 확인하는 로직 추가/#51
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/order/OrderService.java
  src/main/java/com/sparta/icticket/order/dto/OrderCreateRequestDto.java
Labels: Chore

#70 Feat/concurrency/#66
  build.gradle
  src/main/java/com/sparta/icticket/config/AopForTransaction.java
  src/main/java/com/sparta/icticket/config/DistributedLock.java
  src/main/java/com/sparta/icticket/config/RedisConfig.java
  src/main/java/com/sparta/icticket/config/RedissonLockAspect.java
  src/main/java/com/sparta/icticket/config/SchedulerConfig.java
  src/main/java/com/sparta/icticket/performance/Performance.java
  src/main/java/com/sparta/icticket/performance/PerformanceController.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepository.java
  src/main/java/com/sparta/icticket/performance/PerformanceService.java
  src/main/java/com/sparta/icticket/seat/SeatRepository.java
  src/main/java/com/sparta/icticket/seat/SeatService.java
  src/main/java/com/sparta/icticket/seat/dto/SeatReservedRequestDto.java
  src/main/resources/application.yml
  src/test/java/com/sparta/icticket/ConcurrencyTest.java
  src/test/java/com/sparta/icticket/CreateDummyData.java
Labels: Feat

#72 Refactor/code/#71
  src/main/java/com/sparta/icticket/admin/controller/AdminPerformanceController.java
  src/main/java/com/sparta/icticket/admin/controller/AdminSalesController.java
  src/main/java/com/sparta/icticket/admin/controller/AdminSeatController.java
  src/main/java/com/sparta/icticket/admin/controller/AdminSessionController.java
  src/main/java/com/sparta/icticket/admin/controller/AdminVenueController.java
  src/main/java/com/sparta/icticket/admin/service/AdminPerformanceService.java
  src/main/java/com/sparta/icticket/admin/service/AdminSalesService.java
  src/main/java/com/sparta/icticket/admin/service/AdminSeatService.java
  src/main/java/com/sparta/icticket/admin/service/AdminSessionService.java
  src/main/java/com/sparta/icticket/comment/CommentController.java
  src/main/java/com/sparta/icticket/common/config/AopForTransaction.java
  src/main/java/com/sparta/icticket/common/config/CorsConfig.java
  src/main/java/com/sparta/icticket/common/config/DistributedLock.java
  src/main/java/com/sparta/icticket/common/config/JpaConfig.java
  src/main/java/com/sparta/icticket/common/config/PropertyConfig.java
  src/main/java/com/sparta/icticket/common/config/RedisConfig.java
  src/main/java/com/sparta/icticket/common/config/RedissonLockAspect.java
  src/main/java/com/sparta/icticket/common/config/SchedulerConfig.java
  src/main/java/com/sparta/icticket/common/config/SecurityConfig.java
  src/main/java/com/sparta/icticket/common/config/WebConfig.java
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/common/exception/ExceptionManager.java
  src/main/java/com/sparta/icticket/common/security/UserDetailsImpl.java
  src/main/java/com/sparta/icticket/common/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/icticket/common/security/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/icticket/common/security/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/icticket/common/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/icticket/common/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/sparta/icticket/common/security/jwt/JwtExceptionFilter.java
  src/main/java/com/sparta/icticket/common/security/jwt/JwtUtil.java
  src/main/java/com/sparta/icticket/like/LikeController.java
  src/main/java/com/sparta/icticket/like/LikeService.java
  src/main/java/com/sparta/icticket/order/Order.java
  src/main/java/com/sparta/icticket/order/OrderController.java
  src/main/java/com/sparta/icticket/order/OrderRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/order/OrderService.java
  src/main/java/com/sparta/icticket/sales/Sales.java
  src/main/java/com/sparta/icticket/sales/dto/SalesAddRequestDto.java
  src/main/java/com/sparta/icticket/sales/dto/SalesUpdateRequestDto.java
  src/main/java/com/sparta/icticket/seat/Seat.java
  src/main/java/com/sparta/icticket/seat/SeatRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/seat/SeatService.java
  src/main/java/com/sparta/icticket/seat/dto/SeatCreateRequestDto.java
  src/main/java/com/sparta/icticket/session/Session.java
  src/main/java/com/sparta/icticket/session/SessionRepository.java
  src/main/java/com/sparta/icticket/session/dto/CreateSessionRequestDto.java
  src/main/java/com/sparta/icticket/session/dto/UpdateSessionRequestDto.java
  src/main/java/com/sparta/icticket/ticket/OrderAndSeatQueryDto.java
  src/main/java/com/sparta/icticket/ticket/TicketRepositoryQuery.java
  src/main/java/com/sparta/icticket/ticket/TicketRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/user/UserController.java
Labels: Refactor
