Repository S-C-S-D/ICTicket-BackEnd, pull requests merged in 2024-08, with the labels that each got.

#76 Create gradle.yml
  .github/workflows/gradle.yml
Labels: Feat

#78 Feat/docker/#77
  Dockerfile
Labels: Feat

#85 Refactor/performances/#83 java docs
  src/main/java/com/sparta/icticket/admin/controller/AdminBannerController.java
  src/main/java/com/sparta/icticket/admin/controller/AdminPerformanceController.java
  src/main/java/com/sparta/icticket/admin/controller/AdminVenueController.java
  src/main/java/com/sparta/icticket/admin/service/AdminBannerService.java
  src/main/java/com/sparta/icticket/admin/service/AdminPerformanceService.java
  src/main/java/com/sparta/icticket/admin/service/AdminVenueService.java
  src/main/java/com/sparta/icticket/banner/BannerController.java
  src/main/java/com/sparta/icticket/banner/BannerRepository.java
  src/main/java/com/sparta/icticket/banner/BannerService.java
  src/main/java/com/sparta/icticket/performance/PerformanceController.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepository.java
  src/main/java/com/sparta/icticket/performance/PerformanceRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/performance/PerformanceService.java
Labels: Refactor

#90 Seat/Sales/Ticket/Like 리팩토링
  src/main/java/com/sparta/icticket/admin/controller/AdminSalesController.java
  src/main/java/com/sparta/icticket/admin/controller/AdminSeatController.java
  src/main/java/com/sparta/icticket/admin/service/AdminSalesService.java
  src/main/java/com/sparta/icticket/admin/service/AdminSeatService.java
  src/main/java/com/sparta/icticket/like/Like.java
  src/main/java/com/sparta/icticket/like/LikeController.java
  src/main/java/com/sparta/icticket/like/LikeRepository.java
  src/main/java/com/sparta/icticket/like/LikeService.java
  src/main/java/com/sparta/icticket/sales/Sales.java
  src/main/java/com/sparta/icticket/sales/SalesRepository.java
  src/main/java/com/sparta/icticket/seat/Seat.java
  src/main/java/com/sparta/icticket/seat/SeatController.java
  src/main/java/com/sparta/icticket/seat/SeatRepository.java
  src/main/java/com/sparta/icticket/seat/SeatRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/seat/SeatService.java
  src/main/java/com/sparta/icticket/seat/dto/SeatCreateRequestDto.java
  src/main/java/com/sparta/icticket/ticket/Ticket.java
  src/main/java/com/sparta/icticket/ticket/TicketRepository.java
Labels: Refactor

#95 Fix/seat order/#92
  src/main/java/com/sparta/icticket/common/enums/ErrorType.java
  src/main/java/com/sparta/icticket/order/OrderService.java
  src/main/java/com/sparta/icticket/order/dto/OrderCreateRequestDto.java
  src/main/java/com/sparta/icticket/seat/Seat.java
  src/main/java/com/sparta/icticket/seat/SeatController.java
  src/main/java/com/sparta/icticket/seat/SeatRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/seat/SeatService.java
  src/test/java/com/sparta/icticket/ConcurrencyTest.java
  src/test/java/com/sparta/icticket/CreateDummyData.java
Labels: Fix

#98 Main
  src/main/java/com/sparta/icticket/common/config/CorsConfig.java
  src/main/java/com/sparta/icticket/common/config/WebConfig.java
Labels: Feat

#99 Main
  src/main/java/com/sparta/icticket/common/config/CorsConfig.java
  src/main/java/com/sparta/icticket/common/config/WebConfig.java
Labels: Chore

#101 [Refactor] banner startAt, endAt 추가 #100
  http/Banner.http
  src/main/java/com/sparta/icticket/banner/Banner.java
  src/main/java/com/sparta/icticket/banner/BannerRepository.java
  src/main/java/com/sparta/icticket/banner/BannerRepositoryQuery.java
  src/main/java/com/sparta/icticket/banner/BannerRepositoryQueryImpl.java
  src/main/java/com/sparta/icticket/banner/BannerService.java
  src/main/java/com/sparta/icticket/banner/dto/BannerRequestDto.java
Labels: Refactor

#105 테스트코드 이전 정리
  build.gradle
  src/main/java/com/sparta/icticket/banner/Banner.java
  src/main/java/com/sparta/icticket/performance/Performance.java
  src/main/java/com/sparta/icticket/sales/Sales.java
  src/main/java/com/sparta/icticket/seat/Seat.java
  src/main/java/com/sparta/icticket/seat/dto/SeatReservedRequestDto.java
  src/main/java/com/sparta/icticket/session/Session.java
  src/main/java/com/sparta/icticket/user/dto/UserSignupRequestDto.java
  src/main/java/com/sparta/icticket/venue/Venue.java
  src/test/java/com/sparta/icticket/ConcurrencyTest.java
  src/test/java/com/sparta/icticket/CreateDummyData.java
  src/test/java/com/sparta/icticket/admin/controller/AdminPerformanceControllerTest.java
Labels: Chore

#110 [Test] Performance 테스트 코드 작성 #109
  src/test/java/com/sparta/icticket/admin/service/AdminPerformanceServiceTest.java
  src/test/java/com/sparta/icticket/performance/PerformanceServiceTest.java
Labels: Test
